apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: {{ .Release.Name }}
  name: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: nginx
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx
    spec:
      containers:
      - image: {{ .Values.container.image }}
        name: nginx
        ports:
        - name: nginx
          containerPort: {{ .Values.container.port }}
        livenessProbe:
          httpGet:
            path: /
            port: nginx
          initialDelaySeconds: {{ .Values.liveness.initialDelay }}
          periodSeconds: {{ .Values.liveness.period }}
          timeoutSeconds: {{ .Values.liveness.timeout }}
        readinessProbe:
          httpGet:
            path: /
            port: nginx
          initialDelaySeconds: {{ .Values.readiness.initialDelay }}
          periodSeconds: {{ .Values.readiness.period }}
          timeoutSeconds: {{ .Values.readiness.timeout }}
        resources:
          limits:
            cpu: {{ .Values.limits.cpu }}
            memory: {{ .Values.limits.memory }}
          requests:
            cpu: {{ .Values.requests.cpu }}
            memory: {{ .Values.requests.memory }}
        resources: {}
status: {}
