apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: {{ .Release.Name }}
  name: {{ .Release.Name }}
spec:
  ports:
  - port: {{ .Values.service.port}}
    protocol: TCP
    targetPort: {{ .Values.service.port}}
    nodePort: {{ .Values.service.nodePort}}
  selector:
    app: nginx
  type: NodePort
status:
  loadBalancer: {}
